
Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |vb|
        	vb.cpus = 2
        	vb.memory = "1024"
  	end
	config.vm.provision "shell", inline: "echo Hello05"

	config.vm.define "centos" do |centos|
  	 	config.vm.network "forwarded_port", guest: 80, host: 3272
		centos.vm.box = "centos/7"
		centos.vm.provision "shell",inline: $centos
  	end

  	config.vm.define "ubuntu" do |ubuntu|
		config.vm.network "forwarded_port", guest: 80, host: 1223
    		ubuntu.vm.box = "ubuntu/bionic64"
		ubuntu.vm.provision "shell",inline: $ubuntu
  	end
end

$ubuntu = <<-SCRIPT
	mkdir meltsov
	apt install -y httpd
	systemctl enable httpd.service
	systemctl restart httpd.service
SCRIPT
$centos = <<-SCRIPT
	mkdir meltsov
	yum install -y httpd
	systemctl enable httpd.service
	systemctl restart httpd.service
SCRIPT
