
Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |vb|
        	vb.cpus = 2
        	vb.memory = "1024"
  	end
	config.vm.provision "shell", inline: "echo Hello05"

	config.vm.define "centos" do |centos|
  	 	config.vm.network "forwarded_port", guest: 80, host: 8080
		web.vm.box = "centos/7"
		config.vm.provision "shell",inline: $apache
  	end

  	config.vm.define "ubuntu" do |ubuntu|
		config.vm.network "forwarded_port", guest: 80, host: 8080
    		db.vm.box = "ubuntu/bionic64"
		config.vm.provision "shell",inline: $apache
  	end
end

$apache = <<-SCRIPT
	npm install -y httpd
	systemctl enable httpd.service
	systemctl restart httpd.service
SCRIPT
