
Vagrant.configure("2") do |config|
  config.vm.define "centos" do |centos|
  centos.vm.box = "centos/7"
  centos.vm.network "forwarded_port", guest: 80, host: 8080
  centos.vm.synced_folder "./meltsov", "/home/vagrant/"
  centos.vm.provision "shell",inline: " docker-compose up "
end
 